
NAME = open5gs
DESCRIPTION = "4G Network Topology example based on Open5Gs"
CONTAINERS = sidecar-nse webui hss mme
PODS = hss-db web-ui hss 
NETWORK_SERVICES = 4g-network
CHECK = scripts/check-connectivity.sh

include $(TOP)/mk/targets.mk
