---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: open5gs-sgw-deployment
  namespace: open5gs
  labels:
    epc-mode: sgw
spec:
  replicas: 1
  serviceName: "open5gs-sgw-svc-pool"
  selector:
    matchLabels:
      epc-mode: sgw
  template:
    metadata:
      labels:
        epc-mode: sgw
    spec:
      containers:
        - name: sgw
          image: registry.gitlab.com/infinitydon/registry/open5gs-aio:v1.2.0
          imagePullPolicy: Always
          command: ["open5gs-sgwd", "-c", "/open5gs/config-map/sgw.yaml"]
          volumeMounts:
            - name: open5gs-sgw-config
              mountPath: /open5gs/config-map/sgw.yaml
              subPath: "sgw.yaml"
      volumes:
        - name: open5gs-sgw-config
          configMap:
            name: open5gs-sgw-config
metadata:
  name: "s-gw-c"
  namespace: default
  annotations:
    ns.networkservicemesh.io: 4g-network/s11?app=s11,4g-network/s5s8c?app=s5s8-c,4g-network/sxa?app=sxa
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-sgw-config
  namespace: open5gs
  labels:
    epc-mode: sgw
data:
  sgw.yaml: |
    logger:
        file: /var/log/open5gs/sgw.log
    
    parameter:
        no_ipv6: true
    
    sgw:
        gtpc:
           dev: eth0
        gtpu:
           dev: eth0        
